server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://192.168.2.117:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  application:
    zipkin: http://192.168.2.186:9411
  datasource:
    url: jdbc:oracle:thin:@192.168.2.247:1521/ORCLPDB
    username: gcip
    password: gcip
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: false
    hibernate: 
      ddl-auto: none
    generate-ddl: false
    properties: 
      hibernate:
        proc:
          param_null_passing: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
t4i:
  sas:
    bic:
      app:
        formatoFecha: dd/MM/yyyy
        generar:
          log:
            id: 0
        expire-token: 180000
admin-paths:
  paths:
    - uri: "/auth/create"
      method: "POST"