server:
  port: 8090
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**, /api/auth/**, /rest/auth/**
          filters:
            - AuthFilter
        - id: transversal-service
          uri: lb://transversal-service
          predicates:
            - Path=/generales/**, /api/generales/**, /rest/generales/** 
          filters:
            - AuthFilter
        - id: monitor-motor-service
          uri: lb://monitor-motor-service
          predicates:
            - Path=/monitor/motor/**, /api/monitor/motor/**, /rest/monitor/motor/**
          filters:
            - AuthFilter       
        - id: monitor-service
          uri: lb://monitor-service
          predicates:
            - Path=/monitor/dashboard/**, /api/monitor/dashboard/**, /rest/monitor/dashboard/**
          filters:
            - AuthFilter      
        - id: forestal-service
          uri: lb://forestal-service
          predicates:
            - Path=/forestal/**, /api/forestal/**, /rest/forestal/** 
          filters:
            - AuthFilter
        - id: valorizacion-service
          uri: lb://valorizacion-service
          predicates:
            - Path=/valorizacion/**, /api/valorizacion/**, /rest/valorizacion/**
          filters:
            - AuthFilter
        - id: almacen-service
          uri: lb://almacen-service
          predicates:
            - Path=/almacen/**, /api/almacen/**, /rest/almacen/** 
          filters:
            - AuthFilter
        - id: reporteador-service
          uri: lb://reporteador-service
          predicates:
            - Path=/reporteador/**, /api/reporteador/**, /rest/reporteador/** 
          filters:
            - AuthFilter
        - id: proyectos-service
          uri: lb://proyectos-service
          predicates:
            - Path=/proyectos/**, /api/proyectos/**, /rest/proyectos/** 
          filters:
            - AuthFilter
        - id: lims-service
          uri: lb://lims-service
          predicates:
            - Path=/laboratorio/**, /api/laboratorio/**, /rest/laboratorio/** 
          filters:
            - AuthFilter
  jackson: 
    default-property-inclusion: NON_NULL

t4i:
  sas:
    bic:
      app:
        validate-token: http://auth-service/auth/validate?token=