server:
  port: 8090
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://192.168.1.12:8761/eureka
  instance:
    preferIpAddress: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: monitor-motor-service
          uri: lb://monitor-motor-service
          predicates:
            - Path=/monitor/motor/**, /api/monitor/motor/**, /rest/monitor/motor/**
          filters:
            - AuthFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**, /api/auth/**, /rest/auth/**
          filters:
            - AuthFilter
        - id: monitor-service
          uri: lb://monitor-service
          predicates:
            - Path=/monitor/dashboard/**, /api/monitor/dashboard/**, /rest/monitor/dashboard/**
          filters:
            - AuthFilter
        - id: transversal-service
          uri: lb://transversal-service
          predicates:
            - Path=/generales/**, /api/generales/**, /rest/generales/** 
          filters:
            - AuthFilter
  jackson: 
    default-property-inclusion: NON_NULL

t4i:
  sas:
    bic:
      app:
        validate-token: http://auth-service/auth/validate?token=