server:
  port: 7073
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.2.247:1521/ORCLPDB
    username: MONITOR_DB
    password: MONITORDB
    driver-class-name: oracle.jdbc.OracleDriver